### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by MGatner** [nimbly/Limber#2]
Any plans to support PHP 8?

**Comment by brentscheffler** [comment]
Definitely - just waiting for full release.

**Comment by brentscheffler** [comment]
I tested locally using a PHP8-RC5 docker image and all unit tests passed after upgrading PhpUnit and other dev dependencies. We will have to drop PHP 7.2 support though because latest version of PhpUnit does not support it either. Unless of course we keep 7.2 support and drop automated testing of 7.2 in the Travis file.

**Comment by MGatner** [comment]
Great news! No worries on `7.2`, support drops for it November 30 - I think most devs who are moving to support `8.0` will drop `7.2` at the same time (or at least only maintain it on legacy branches).
[<img width="971" alt="Screen Shot 2020-11-23 at 2 36 07 PM" src="https://user-images.githubusercontent.com/17572847/100007009-5e48af00-2d99-11eb-8c0f-db9ba1aa270f.png">](https://www.php.net/supported-versions.php)

**Comment by MGatner** [comment]
Talk about the long game 💪
